print("Enter the Name of a File to Read: ", end="")
file1 = input()
handle1 = open(file1, "r")
content = handle1.read()
handle1.close()
file2= str(input("Enter the Name of a File to Write: "))
handle2= open(file2, "w+")
file2= str(content)
c = input("ENTER CHARACTER YOU WANT TO REPLACE  : ")
r = input("ENTER CHARACTER YOU WANT TO REPLACE WITH : ")
handle2.write(content.replace(c,r))
handle2.close()